name = input("请输入您的姓名：")
company = input("请输入您的公司：")
title = input("请输入您的职位：")
phone = input("请输入您的电话：")
email = input("请输入您的邮箱：")
print("****************************")
print("姓名：", name)
print("公司：%s" % company)
print("职位：", title)
print("电话：%s" % phone)
print("邮箱：", email)
print("****************************")